### ISSUE TITLE
Possible Error in the methanol example?

### ISSUE THREAD

**Issue by wwang2** [noid-group/BOCS#1]
I have a problem running AA simulation for the 1-site methanol example, it is a GROMACS error. 
I have just started to try to play with BOCS, but I am really new to GROMACS. 

When I issue the command
` grompp -f methanol.mdp -c methanol.gro -p methanol.top -o methanol.tpr`

It produces the following error:

> Program gmx grompp, VERSION 5.1.2
Source code file: /build/gromacs-z6bPBg/gromacs-5.1.2/src/gromacs/gmxpreprocess/topio.c, line: 661
Fatal error:
Syntax error - File ffoplsaa.itp, line 1
Last line read:
'
#error   This top-level .itp file has been removed. Edit your topology to include it from your force field directory instead, e.g. "oplsaa.ff/forcefield.itp" etc.'
For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors

Hope this is the right place to bring this issue up.

**Comment by njhdunn** [comment]
This test was originally developed under gromacs 4.5.3, when the ffoplsaa.itp file was a top-level file in the gromacs force field directory. You can edit line #1 in methanol.top to read:
`#include "oplsaa.ff/forcefield.itp"`
and it should work in gromacs 5.1. I've committed the change here as well so any new pulls from the repository will be gromacs 5.x compatible.

**Comment by wwang2** [comment]
Solved. That was easy. Thanks !!

**Comment by Sadiyahafroz** [comment]
I have question , related to the same error what if i am not using OPLS force field?

**Comment by rszukalo** [comment]
> 

The algorithm can work with any force field, it does not have to be OPLS.  The force-matching algorithm uses whatever forces are present in the trajectory, regardless of the force field used.
