### ISSUE TITLE
Need help to coarse-grain dodecane

### ISSUE THREAD

**Issue by bagayang** [noid-group/BOCS#15]
Hello,

### Problem:
when I use the follow command, it fails to get the `cg.dode.tpr` file 

``` 
gmx grompp -f dode_cg.mdp cg.dode.tpr-p dode_cg.top -n dode_cg.ndx -c cg.dode.gro -o cg.dode.tpr
```

### Enviroment:
OS: centOS 7
Gromacs:  5.1.4

### Source of files:
|file|Description|
|:-:|:-:|
|dode_cg.top|refer the file `cg.1_1_HEP_TOL.top` in BOCS tutorials and manually modify|
|dode_cg.ndx|refer the file `cg.1_1_HEP_TOL.ndx` in BOCS tutorials and manually modify|
|dode_cg.mdp|refer the file `cg.1_1_HEP_TOL.mdp` in BOCS tutorials and manually modify|
|map.dode.top|refer the file `map.1_1_HEP_TOL.top` in BOCS tutorials and manually modify|
|dode_aa.trr|transfrom the output file file.xtc got from LAMMPS, do not include the velocity information |
|cg.dode.gro|get from the command `cgmap -f dode_aa.trr -p map.dode.top -c cg.dode.gro`|

### Output massage:
```
Command line:
  gmx grompp -f dode_cg.mdp -p dode_cg.top -n dode_cg.ndx -c cg.dode.gro -o cg.dode.tpr

Ignoring obsolete mdp entry 'title'
Ignoring obsolete mdp entry 'cpp'
Replacing old mdp entry 'nstxtcout' by 'nstxout-compressed'

Back Off! I just backed up mdout.mdp to ./#mdout.mdp.8#

NOTE 1 [file dode_cg.mdp]:
  The group cutoff scheme is deprecated since GROMACS 5.0 and will be
  removed in a future release when all interaction forms are supported for
  the verlet scheme. The verlet scheme already scales better, and it is
  compatible with GPUs and other accelerators.


NOTE 2 [file dode_cg.mdp]:
  nstcomm < nstcalcenergy defeats the purpose of nstcalcenergy, setting
  nstcomm to nstcalcenergy


WARNING 1 [file dode_cg.mdp]:
  You are generating velocities so I am assuming you are equilibrating a
  system. You are using Parrinello-Rahman pressure coupling, but this can
  be unstable for equilibration. If your system crashes, try equilibrating
  first with Berendsen pressure coupling. If you are not equilibrating the
  system, you can probably ignore this warning.

Setting the LD random seed to 3339339268

WARNING 2 [file mdp file]:
  Malformed include option $HOME/_github/gromacs-5.1.4/share/top/

Generated 0 of the 1 non-bonded parameter combinations
Excluding 4 bonded neighbours molecule type 'dode'
Warning: atom name 1 in dode_cg.top and cg.dode.gro does not match (CM - CMA)
Warning: atom name 2 in dode_cg.top and cg.dode.gro does not match (CM - CMB)
Warning: atom name 3 in dode_cg.top and cg.dode.gro does not match (CM - CMC)
Warning: atom name 4 in dode_cg.top and cg.dode.gro does not match (CM - CMD)
Warning: atom name 5 in dode_cg.top and cg.dode.gro does not match (CM - CMA)
Warning: atom name 6 in dode_cg.top and cg.dode.gro does not match (CM - CMB)
Warning: atom name 7 in dode_cg.top and cg.dode.gro does not match (CM - CMC)
Warning: atom name 8 in dode_cg.top and cg.dode.gro does not match (CM - CMD)
Warning: atom name 9 in dode_cg.top and cg.dode.gro does not match (CM - CMA)
Warning: atom name 10 in dode_cg.top and cg.dode.gro does not match (CM - CMB)
Warning: atom name 11 in dode_cg.top and cg.dode.gro does not match (CM - CMC)
Warning: atom name 12 in dode_cg.top and cg.dode.gro does not match (CM - CMD)
Warning: atom name 13 in dode_cg.top and cg.dode.gro does not match (CM - CMA)
Warning: atom name 14 in dode_cg.top and cg.dode.gro does not match (CM - CMB)
Warning: atom name 15 in dode_cg.top and cg.dode.gro does not match (CM - CMC)
Warning: atom name 16 in dode_cg.top and cg.dode.gro does not match (CM - CMD)
Warning: atom name 17 in dode_cg.top and cg.dode.gro does not match (CM - CMA)
Warning: atom name 18 in dode_cg.top and cg.dode.gro does not match (CM - CMB)
Warning: atom name 19 in dode_cg.top and cg.dode.gro does not match (CM - CMC)
Warning: atom name 20 in dode_cg.top and cg.dode.gro does not match (CM - CMD)
(more than 20 non-matching atom names)

WARNING 3 [file dode_cg.top, line 51]:
  200 non-matching atom names
  atom names from dode_cg.top will be used
  atom names from cg.dode.gro will be ignored


Velocities were taken from a Maxwell distribution at 298 K

-------------------------------------------------------
Program gmx grompp, VERSION 5.1.4
Source code file: /home/yang/_github/gromacs-5.1.4/src/gromacs/gmxpreprocess/readir.c, line: 2599

Fatal error:
Group CM referenced in the .mdp file was not found in the index file.
Group names must match either [moleculetype] names or custom index group
names, in which case you must supply an index file to the '-n' option
of grompp.
```

### Description:

The message said CM in mdp file can not find in the index file .But I compare the files with the files in tutorials, I think there is not much difference.

Can give me some advice to solve the problem?
Although it’s not the software problem, I don’t know where to ask .

[source files](https://1drv.ms/u/s!Aijra80UaxorjLoCYqKz8i4WZQXysg?e=YnC5vF)

Many thanks,

Yang

**Comment by kml5480** [comment]
Yang - 

The coarse-grained sites indicated in the .mdp file must match the list in the index file. So if you don't have a site called "CM" in dodecane, you should remove that site name from the "energy-grps" list in the .mdp file (or if you do have a CM site in the molecule, add that entry to the index file).

Thanks,
Kate

**Comment by bagayang** [comment]
Kate -

Thanks for  your advice, and sorry to reply you so late.
I divide the dodecane into four coarse-grained sites(CMA, CMB, CMC, CMD) and write in the ndx file, but not write  [CM]. So I add it and try again. But this time it also has error.  Even if I use the follow command, it also has error.

Is my modification wrong?

Many thanks,

Yang

```
gmx grompp -f dode_cg.mdp -p dode_cg.top -n dode_cg.ndx -c cg.dode.gro -o cg.dode.tpr -maxwarn 1
```

```
Velocities were taken from a Maxwell distribution at 298 K
Number of degrees of freedom in T-Coupling group System is 597.00
This run will generate roughly 5 Mb of data

There were 2 notes

There were 3 warnings

-------------------------------------------------------
Program gmx grompp, VERSION 5.1.4
Source code file: /home/yang/_github/gromacs-5.1.4/src/gromacs/gmxpreprocess/grompp.c, line: 2107

Fatal error:
Too many warnings (3), gmx terminated.
If you are sure all warnings are harmless, use the -maxwarn option.
For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors

```

**Comment by kml5480** [comment]
Yang - 

The error you posted comes from Gromacs, not BOCS. You have 3 warnings, but only one is permitted according to the "-maxwarn 1" flag. I think you have to clear up what's causing those warnings, in addition to adding your sites to the "energy-grps" list in the dode_cg.mdp file (i.e. "energy-grps = CMA CMB CMC CMD", without the quotations).

As a side note, what distinguishes CMA and CMD from each other (and CMB and CMC)? They should be chemically equivalent.

Thanks,
Kate

**Comment by bagayang** [comment]
Kate -

Thanks for your reply and advice.

CMA、CMB、CMC and CMD are chemically equivalent as you said. They are the same type of coarse-grained sites ,so I use the same description method as the files in BOCS tutorials . 

Sorry, I have the misunderstand of the flags of  `maxwarn ` before ,when I use `-maxwarn 3`, I can get the `cg.dode.tpr`  file. Then I check the warnings description ,they are the same as the result of my test of BOCS tutorials. So I think it may not be important.

Then when I use `mpirun cgff` to get the force filed, it can not output the `f_forces`  files. I try to use `f_struct` files to replace `f_forces` files in the description in `par.txt` , but it put the follow massage. The elements 2 and 3 are `f_struct.Angle.total.Angle_CM-CM-CM.dat` and `f_struct.BondStretch.total.Bond_CM-CM.dat`
I think the possible reason is that the trr file of AA I use is not included the velocity information. 

I'm sorry to keep asking some questions related to my modification of files instead of BOCS bug related.

Many thanks,
Yang
```
ERROR: Grid points for r not evenly spaced in input file.
-----Check spacing between elements 2 and 3.
```

**Comment by kml5480** [comment]
Yang - 

Again, the error is in naming your CG sites. As I mentioned before, site naming across all Gromacs and BOCS files has to be consistent. It appears that the sites are labelled as "CM" in some of your files and "CMA/CMB/CMC/CMD" in others. This is responsible for part, if not all of the issues you are seeing. If you increase the "maxwarn" flag for pre-processing in Gromacs, you're just going to mask this site naming discrepancy and it'll cause problems further down the line.

I'm sorry if it wasn't clear before, but you need to fix that first. Your .gro, .top, and .mdp files all need to have the same site types. Once you fix that, you can re-grompp without "maxwarn" and see what issues come up, but I think these are all stemming from not having consistent site type names and trying to push through anyway.

Thanks,
Kate

**Comment by rszukalo** [comment]
Hi Yang,

I wanted to follow up on this.  Were you able to get this error sorted out?  Or is there more you would like assistance with?

Thanks
Ryan

**Comment by bagayang** [comment]
Hi Kate and Ryan

I'm sorry for the late reply.
I think Kate`s advice is right, but if when I change all the "CM" to "CMA/CMB/CMC/CMD", it will become very cumbersome, and make error easier than before. I think the method of the BOCS tutorials is more convenient for me. And the warrings of GROMACS, I think it is harmless.

The problem for me now is that though I can run the code `mpirun cgff`, I cannot get `f_forces` files.

The possible reason is that the trr file of AA I use is not included the velocity information. I try to get the velocity information in xtc file from LAMMPS, but fail.

Is BOCS can only use the all-atoms simulation data from GROMACS? Or are there other ways to use LAMMPS dumps 

Sorry again for the late reply.

Many thanks,
Yang

**Comment by kml5480** [comment]
Yang - 

I know changing all the site type names for consistency is a pain - perhaps scripting that change could help? But it's the only way you'll get meaningful results out of BOCS.

RE the lack of `f_forces` files, did both your original AA trajectory and mapped trajectory (the AA trajectory in CG representation) have forces saved? If they aren't present in the AA trajectory, force matching will not be possible. If they are present in the AA trajectory, when you called `gmx trjconv`, if you didn't include the flag `-force`, the forces will be left out of the mapped trajectory by default.

Thanks,
Kate

**Comment by mdelyser** [comment]
Yang,

You should be able to use bocs' translator to turn a lammps dump file into a .trr file. In your lammps input file, use something along the lines of

dump dumpid all custom 1000 dump.lmp id x y z fx fy fz

you can include more properties if you would like, but these seven are needed at a minimum. After the simulation is done, you can translate it into a .trr file

~/path/to/bocs/translator -f dump.lmp -o dodecane.trr

Let me know if you run into any trouble with this.

Regards,

Michael

**Comment by bagayang** [comment]
Michael,

Thanks for advice. I can make all-atom.trr easier than before. But also have a trouble. 

Now I run `mpirun cgff`  ,I can get `f_forces` file ,but when I run `sh make_gmx_table.sh` ,it get the follow massage:

>ERROR: Grid points for r not evenly spaced in input file.
>-----Check spacing between elements 2 and 3.

I can see `table_a0.xvg` ,`table_CM_CM.xvg`, but `table_b1.xvg` is 0 KB
`b_forces.BondStretch.total.Bond_CM-CM.dat`  has breakpoint at first, like this:
>0.12500          0.18525
>0.12600          2.37379
>0.13800          2.59815
>0.13900          6.53049
>0.14500         -6.97923
>0.14600         -2.39071
>0.14900         -1.87663

I try to delete the uneven line and modify the range in sh file, but also have the same error.

I hope it will be the last error in BOCS force matching in my case and sorry for not being able to reply in time.
[source of my f_force and sh files](https://1drv.ms/u/s!Aijra80UaxorjL5pdLwotCMtwA4w_g?e=WcNt6b)

Many thanks,
Yang

**Comment by mdelyser** [comment]
so it looks like you had sampling of abnormally short CG bonds. get rid of the first six lines so the first line in the file is 0.14900 -1.87663. Then the tables program should work.

**Comment by mdelyser** [comment]
Hi Yang,

Delete the first six lines of the f_forces.BondStretch.total.Bond_CM-CM.dat file. Then it should work.

Also, you included your b_forces.* files in that zip, not your f_forces.* files. I looked at the b_forces.BondStretch.total.Bond_CM-CM.dat file. It appears to me that you need to rerun force matching and increase the maximum cg bond length in your par.txt file. You should be able to use gromacs to calculate bond length distribution from your coarse-grained trajectory. I would advise doing this to verify that all bond lengths sampled in the trajectory are included in the range you specify in the par.txt file. 

Regards,

Michael DeLyser

**Comment by bagayang** [comment]
Michael,

Thanks, I delete the uneven lines ,it works．Finally, I get the the table files for Lammps.
I will try to use gromacs to calculate bond length distribution and reply later.(If not meet the new error,I will close this issue later)

I think it is OK for force matching in my case, and will try pressure matching later.
If I meet problem, I will put new issue.

Many thanks,
Yang

**Comment by mdelyser** [comment]
Yang,

I'm glad you got it to work.

However, I still think you need to force match your system again after increasing the range for the CG bond lengths in your par.txt file. Change it so the maximum is 0.5 nm. 

Regards,

Michael DeLyser
