### ISSUE TITLE
Error in Bspline force coefficients

### ISSUE THREAD

**Issue by JFRudzinski** [noid-group/BOCS#16]
Hi again,

We've found an error in the output files f_forces_coeff.XXX.dat. **Please note that this should not affect any previous results that I am aware of as it only has to do with the coeff files and does not extend to the f_forces.XXX.dat files, i.e., the interpolated forces used for simulations.**

In the function print_Bspline_basis_forces() in io_output.c:

  /* Print results. */

  /* print the coefficients calculated */
  for (j = 0; j < inter->N_pts; j++) {
     ptr_x = inter->ptr_x[j];
     /* Account for angle and dihedral forces in degrees. */
     if ((strcmp(B_ANGLE, inter->inter_type) == 0)
       || (strcmp(B_DIHEDRAL, inter->inter_type) == 0)) {
       ptr_x *= 180.0 / M_PI;
     }

     fprintf(fp_f_struct_coeff, "%10.5lf  %15.5lf \n", ptr_x,
        inter->ptr_phi_struct[j] * (M_PI / 180.0)); **<--- Here multiplication by (M_PI / 180.0) is incorrect!**
     if (forces) {
       fprintf(fp_f_forces_coeff, "%10.5lf  %15.5lf \n", ptr_x,
          inter->ptr_phi_forces[j] * **(M_PI / 180.0)**); **<--- Here multiplication by (M_PI / 180.0) is incorrect!**
     }
  } 

I have no idea why I multiplied the calculated coefficients by pi/180. This is obviously wrong for non-angle interactions, such that all the printed coefficients are off by this factor. It should also be incorrect for angle interactions since it undoes the transformation from radians to degrees in the above lines. However, I need to keep thinking about this because it seems strange for it to be a random typo...

Again, if you look further down in this function where the f_forces.XXX.dat files are printed, this error does not apply.

Best,

Joe

**Comment by mdelyser** [comment]
Hey Joe,

Two things.

1) After using the spline to evaluate the force at each interpolated value of the angle, we do

       if ((strcmp(B_ANGLE, inter->inter_type) == 0)
        || (strcmp(B_DIHEDRAL, inter->inter_type) == 0)) {
        R *= 180.0 / M_PI;
        f_struct *= M_PI / 180.0;
        if (forces) {
          f_forces *= M_PI / 180.0;
        }

which does indeed change the value of the forces we print out to f_forces.XXX.dat

2) I'm relatively certain you're supposed to multiply by M_PI / 180.0. We calculate the angle forces as a function of theta in radians that returns a force in kJ/mol / radian. When we change theta from radians to degrees, we similarly have to change kJ/mol / radian to kJ/mol / degree. multiplying by M_PI / 180.0 is the correct factor to change kJ/mol / radian to kJ/mol / degree. 

I'll leave this open for now in case you disagree. Please let me know when you've read this and your thoughts.

Best,

Michael

**Comment by JFRudzinski** [comment]
Hi Michael,

Thanks for the quick response.

In print_Bspline_basis_forces(), there are two different sections, the first prints the f_forces_coeff.XXX.dat files. This is what I pasted in my original post and here again with more comments:

  /* Print results. */

  /* print the coefficients calculated */
  for (j = 0; j < inter->N_pts; j++) {
     ptr_x = inter->ptr_x[j];
     /* Account for angle and dihedral forces in degrees. */
     if ((strcmp(B_ANGLE, inter->inter_type) == 0)
       || (strcmp(B_DIHEDRAL, inter->inter_type) == 0)) {
       ptr_x *= 180.0 / M_PI;
     } -- END OF IF ANGLE/DIH STATEMENT!!

     fprintf(fp_f_struct_coeff, "%10.5lf  %15.5lf \n", ptr_x,
        inter->ptr_phi_struct[j] * (M_PI / 180.0));
     if (forces) {
       fprintf(fp_f_forces_coeff, "%10.5lf  %15.5lf \n", ptr_x,
          inter->ptr_phi_forces[j] * (M_PI / 180.0)); -- THIS MULTIPLICATION IS HAPPENING FOR, e.g., PAIR FORCES AS WELL!!
     }
  }

In the second section labeled with the comment   /* print the forces tabulated on a finer grid than the calculation */, we have:

       if ((strcmp(B_ANGLE, inter->inter_type) == 0)
        || (strcmp(B_DIHEDRAL, inter->inter_type) == 0)) {
        R *= 180.0 / M_PI;
        f_struct *= M_PI / 180.0;
        if (forces) {
          f_forces *= M_PI / 180.0;
        }
       } -- END OF IF ANGLE/DIH, MULT BY M_PI / 180.0 ONLY FOR ANGLE/DIH HERE
       fprintf(fp_f_struct, "%10.5lf  %15.5lf \n", R, f_struct);
       if (forces) {
        fprintf(fp_f_forces, "%10.5lf  %15.5lf \n", R, f_forces); -- NORMAL PRINTING FOR, e.g., PAIR FORCES :) 
       }

For your #2 point, thanks for reminding me about the unit conversion...yes, I agree this is correct for ANGLE/DIH interactions. I

So, I still believe we need to change the printing of the f_forces_coeff.XXX.dat files so that they are not multiplied by M_PI/180.0 for non-ANGLE/DIH interactions. Let me know what you think.

Best,

Joe
