### ISSUE TITLE
typo in manual

### ISSUE THREAD

**Issue by sjwoerner** [noid-group/BOCS#2]
Hello,
I tried running BOCS yesterday with the [TPR_EXCL] directive. Is it possible that there is a mistake in the manual and the directive should be named [TOP_EXCL]?

**Comment by mdelyser** [comment]
Hello,

You're right. The manual specifies details for a [TPR_EXCL] directive, but the code expected [TOP_EXCL]. I modified the code so it now searches for TPR_EXCL (like the manual says). Sorry for the confusion, and thank you for bringing this to our attention.
