### ISSUE TITLE
Problem reading multiple trr files

### ISSUE THREAD

**Issue by JFRudzinski** [noid-group/BOCS#3]
Hi guys,

There seems to be a problem with the code whenever you have more than 1 structure file in inp.txt. After the first trajectory is read, the code exits with "ERROR: unable to determine precision of trr file". The function path is main() -> read_first_frame() -> tW_read_first_trr_frame() -> fr->setup_xdr() -> get_trr_precision(). 

I thought there might be a problem with the initialization of "fr" so I tried freeing the memory of "fr" at the end of the loop over topologies and then reinitializing with "fr = init_tW_gmx_trxframe();" but that did not change anything.

I've tested a few different systems and found the same issue. The easiest test is perhaps to use the lj_recovery test in the BOCS distribution. I just took one frame from the trajectory, f1.trr, and copied it to a different filename (e.g., fr1_2.trr), put each of these as different structure file in inp.txt with corresponding topology entries in par.txt. 

It seems to me that you guys must have tested this at some point, especially in the context of the extended ensemble method. So, perhaps I am doing something stupid. Please let me know your thoughts.

Best,

Joe

**Comment by mdelyser** [comment]
Hi Joe,

Thanks for catching this. I tried the same thing you did and got the same error. However, I moved the initialization of fr and fr_ref into the loop over files and then freed the memory at the end of the loop and it worked. This sounds like it's the same thing you tried that didn't work, so I'm not sure what exactly the differences are.

It should work now. If you reclone the repo and it still doesn't work, let me know.

Michael DeLyser

**Comment by JFRudzinski** [comment]
Hi Michael,

Thanks so much for taking a look at that for me. When I ran the new code on
the LJ system it worked perfectly...but then i got a segmentation fault
when I tried it on another set of trajectories (regardless of how many
structure files I have). I have no idea why this happened, perhaps it’s
something strange on my end, but the same trr file reads fine when I run it
with the old version. It crashes in a similar spot (but without throwing an
error), when it is reading the first trr.

Unfortunately, i am traveling now and didn’t have a chance to look into it
further. I will take a look when I get back in a week.

Thanks again and I hope all your work is going wel!

Best,

Joe

**Comment by JFRudzinski** [comment]
Hi Michael,

So, I've performed a few more tests now. For reasons that I (completely!) do not understand, your fix works in the case that there are only nonbonded interactions. As soon as I add bonds to my topology, the current code segfaults when reading the first frame of the first trr file. Here is the gdb backtrace:

#0  0x00007ffff5ed93b0 in fread () from /lib64/libc.so.6
#1  0x00007ffff5f85270 in xdrstdio_getlong () from /lib64/libc.so.6
#2  0x00007ffff5f8402b in xdr_int () from /lib64/libc.so.6
#3  0x000000000043909f in tW_do_read_xdr (fr=0x5044fd0, item=0x7fffffff4f80, nitem=1, eio=0)
    at /data/isilon/rudzinski/soft_backup/BOCS_NEW/BOCS_DEBUG/force-matching/src/gromacs_topology.c:5117
#4  0x000000000043937d in get_trr_precision (fr=0x5044fd0)
    at /data/isilon/rudzinski/soft_backup/BOCS_NEW/BOCS_DEBUG/force-matching/src/gromacs_topology.c:5178
#5  0x000000000042379f in setup_xdr (self=0x5044fd0, fnm=0x6805a0 "../LJ.trr", bRead=1)
    at /data/isilon/rudzinski/soft_backup/BOCS_NEW/BOCS_DEBUG/force-matching/src/gromacs_topology.c:686
#6  0x000000000043a22d in tW_read_first_trr_frame (fr=0x5044fd0, trx_fnm=0x6805a0 "../LJ.trr")
    at /data/isilon/rudzinski/soft_backup/BOCS_NEW/BOCS_DEBUG/force-matching/src/gromacs_topology.c:5342
#7  0x00000000004258cd in read_first_frame (fr=0x5044fd0, fnm=0x6805a0 "../LJ.trr")
    at /data/isilon/rudzinski/soft_backup/BOCS_NEW/BOCS_DEBUG/force-matching/src/gromacs_topology.c:1218
#8  0x0000000000408eea in main (argc=1, argv=0x7fffffffd468) at /data/isilon/rudzinski/soft_backup/BOCS_NEW/BOCS_DEBUG/force-matching/src/cgff.c:205

Now, if I keep the init_tW_gmx_trxframe() outside the loop and then add an if (i!=0){init_tW_gmx_trxframe()} inside the loop over structures, it reads the first trr fine, but segfaults (apparently for the same reason) when reading the second trr file. the fr variable doesn't seem to be used before the loop over structures, so I am very confused at the moment. 

I'm wondering if you can reproduce the error when adding bonds to your top file? Any insight you have would be very much appreciated!

Best,

Joe

**Comment by mdelyser** [comment]
Hi Joe,

I hope your travels went well.

Are you using the most recent version of the code? I just tried running extended ensemble test system (3 trr: 1 frame butane, 1 frame heptane, 1 frame decane) and it worked fine for me. It has 3 pair interactions, 3 bonds, and 2 angles.

If you're running the most recent version and it's still not working, then there must be something odd/unique about your system that the code isn't ready for. If you could email me the .tpr files and a couple frames from each of the .trr files I'll try to figure out what's wrong.

Regards,

Michael

**Comment by JFRudzinski** [comment]
Hi Michael,

Thanks again for your time. 

I re-pulled the new version and everything works now! Sorry about that. I was trying to integrate some other changes that I made to the code, and even though I thought I went back to your newest version when things were not working, I guess something got messed up along the way. You can go ahead and close this issue again.

Best,

Joe
