### ISSUE TITLE
Memory consumption in topology structure

### ISSUE THREAD

**Issue by sjwoerner** [noid-group/BOCS#5]
Hello,

I was trying to run a system with roughly 12.000 sites, and the FIRST_HALF calculation for nonbonded interactions only was using about 16GB of memory. This number also did not change with the number or coefficients. This memory consumption seems to originate from memory allocation for top->contents->atoms in gromacs_topology.c lines 2200-2220. The dependent variables atomname, atomtype, and atomtypeB are each triple pointers of size n_atoms x n_atoms x 10. As a quick fix, I just changed the memory allocation to the following:

for (i = 0; i < n_atoms; ++i)
  {
    (top->contents->atoms.atomname[i]) = (char **) ecalloc(1,sizeof(char *));
    (top->contents->atoms.atomtype[i]) = (char **) ecalloc(1,sizeof(char *));
    (top->contents->atoms.atomtypeB[i]) = (char **) ecalloc(1,sizeof(char *));
  }
  for (i = 0; i < n_atoms; ++i)
  {
        top->contents->atoms.atomname[i][0] = (char *) ecalloc(10,sizeof(char));
        top->contents->atoms.atomtype[i][0] = (char *) ecalloc(10,sizeof(char));
        top->contents->atoms.atomtypeB[i][0] = (char *) ecalloc(10,sizeof(char));
  }

i.e., reduced the dimension of these arrays to n_atoms x 1 x 10. This reduces the memory consumption to less than 1GB and I ran two test systems and got exactly the same results as before.

However, it is not clear to me why these are triple pointers in the first place. All instances of these variables in the code only reference the first dimension. Should these not be defined as double pointers instead with dimension n_atoms x 10?

I would really appreciate your thoughts, because using 16GB of memory makes it impossible to submit it to any cluster I have access to.

Thanks a lot!

**Comment by mdelyser** [comment]
Hello,

Thank you for bringing this to our attention. You're right, the dimensions should be n_atoms x 1 x 10, instead of n_atoms x n_atoms x 10. I updated this in gromacs_topology.c. 

Yes, these could, in theory, be defined as double pointers instead of triple pointers. Long story short, we define them as triple pointers because that's how they're defined in the GROMACS source code. 

Sorry for the delay in addressing this issue.

Michael DeLyser
