### ISSUE TITLE
Index error when building exclusions list

### ISSUE THREAD

**Issue by sjwoerner** [noid-group/BOCS#6]
System: molecular liquid with 1296 molecules, 9 CG sites per molecule, and 3 neighbor exclusions per site.

Error: 
A segmentation fault occurred in gromacs_topology.c in line 242 because it couldn’t access an entry in self→contents→excls.a. The index it was trying to access is stored in self→contents→excls.index and was much greater than the array size of excls.a. 

Description:
Both arrays are constructed in pop_contents() starting at line 2305 of gromacs_topology.c. The entries in excls.a should be the index of the sites to exclude for each site in the system and excls.index stores the index of the first exclusion partner for each site. This means the sum in line 2321 should add the number of exclusions for that site stored in my_mols[i].n_epa[k], not  my_mols[i].n_excls. my_mols[i].n_excls stores the number of atoms in a molecule type that require other atoms to be excluded. 

For a system with zero exclusions (i.e., only self exclusions), this would lead the index to grow by the number of atoms per molecule instead of by 1, since each atom only requires the exclusion of itself. This lead the index to grow much higher than the size of the referenced array.

** C may allow you to access that memory, leading to wrong exclusion lists. Otherwise, if the memory there is not accessible, this problem leads to the segmentation fault described above. Note that this may depend on the specifications of your installation environment. E.g., the segfault initially only occurred on our cluster, not on our desktops.

Solution:
Gromacs_topology.c line 2321 should be changed to 
top->contents->excls.index[at_idx] = top->contents->excls.index[at_idx-1] + my_mols[i].n_epa[k];

**Comment by mdelyser** [comment]
Hello,

Thanks for the detailed explanation of everything and the solution. I fixed the issue in gromacs_topology.c

Sorry for the delayed response.
